# Generated by Django 3.2.4 on 2021-09-16 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='votesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('No_opine', models.ManyToManyField(blank=True, related_name='no', to=settings.AUTH_USER_MODEL)),
                ('categorys', models.ManyToManyField(blank=True, related_name='category', to='votes.category')),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('yes_opine', models.ManyToManyField(blank=True, related_name='yes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
